### PR TITLE
Fixes #15988 - Reduce bottom margin on navigation bar

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by waldenraines** [comment]
Thoughts about using 10px instead of 5px?

**Comment by waldenraines** [comment]
> Thoughts about using 10px instead of 5px?

Actually scratch that, ACK.

**Comment by johnpmitsch** [comment]
@waldenraines thanks! Merge whenever since I don't have permissions :smile:

**Comment by waldenraines** [comment]
> @waldenraines thanks! Merge whenever since I don't have permissions 

Oh yeah, right.

**Pull request merged**
