### PR TITLE
Fixes #23664 - Update the gemspec

### PR DESCRIPTION
**Pull request by ekohl**
* Corrects the homepage
* Sets the license
* Trims trailing whitespace

### CODE REVIEW

**Comment by ekohl** [comment]
[test bastion]

**Comment by ekohl** [comment]
[test bastion]

**Comment by beav** [comment]
[test bastion]

**Comment by beav** [comment]
@ekohl a redmine issue # in the commit msg is required for this one to make prprocessor pass

**Comment by ekohl** [comment]
Added an issue

**Pull request merged**
