### PR TITLE
Fixes #18241: fix datepicker and typeahead dropdown css.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/18241

### CODE REVIEW

**Comment by ehelms** [comment]
This fixes things for me. The assets failure seems to be occurring for all PRs. I will investigate it more.

**Comment by thomasmckay** [comment]
+1 ack from me too

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
> The assets failure seems to be occurring for all PRs. I will investigate it more.

Try, try, try again and it worked 👍

**Pull request merged**
