### PR TITLE
Fixes #10971: upgrade bastion to rails4.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/10971

### CODE REVIEW

**Comment by ehelms** [comment]
This is all it takes to upgrade to Rails 4? I assume this is backwards compatible to 3.2 as well?

**Comment by waldenraines** [comment]
> This is all it takes to upgrade to Rails 4? I assume this is backwards compatible to 3.2 as well?

This is what it takes to get rails started when using rails4 with other rails4 projects.  Unsure if this is backwards compatible so I'm merging to the rails4 branch where there may be future changes before bringing this into master.  The intention was to get rails4 running and the tests passing in an upstream branch so multiple people could work on converting foreman + katello.

**Comment by ehelms** [comment]
I didn't pick up that it was a Rail 4 branch. Similar to the foreman-dev thread, if we can push backwards compatible changes into master, I think the conversion will go smoother in the end.

**Comment by waldenraines** [comment]
> I didn't pick up that it was a Rail 4 branch. Similar to the foreman-dev thread, if we can push backwards compatible changes into master, I think the conversion will go smoother in the end.

I agree, let me test this out with rails 3.2 and see if I can't just open a PR against master instead.

**Comment by waldenraines** [comment]
Closing in favor of https://github.com/Katello/bastion/pull/73

**Pull request closed without merging**
