### PR TITLE
Fixes #9874: prevent redirection to API calls, BZ1118444.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/9874
https://bugzilla.redhat.com/show_bug.cgi?id=1118444

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
ACK

**Pull request merged**
