### PR TITLE
Fixes #18485: add table parameter caching

### PR DESCRIPTION
**Pull request by waldenraines**
Cache the page number, sort, search, etc. on tables so they are
preserved upon state change.

http://projects.theforeman.org/issues/18485

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
Not sure if this is the caching, but I noticed that if I say search for '25' and I have a product named 'Product 25'. I think click on that product and remove it. I am returned back to my table with Product 25 in it even though I just removed it. Or thought I did.

**Comment by ehelms** [comment]
I also saw the following, could be a separate issue:

screenshot from 2017-03-29 15-55-47


Note the NaN in the page selector.

**Comment by ehelms** [comment]
Related, this details table is perma semi-transparent:

screenshot from 2017-03-29 15-58-52

**Comment by waldenraines** [comment]
> Not sure if this is the caching, but I noticed that if I say search for '25' and I have a product named 'Product 25'. I think click on that product and remove it. I am returned back to my table with Product 25 in it even though I just removed it. Or thought I did.

This is becase we are creating a task for the removal of the product and then not notifying the user about it.  It's a known bug but it's unrelated to the table caching.  If you try the same thing on, say, activation keys, it behaves correctly.   See http://projects.theforeman.org/issues/18683.

> Note the NaN in the page selector.

How did you cause that to happen?

**Comment by waldenraines** [comment]
> Related, this details table is perma semi-transparent:

That seems to be a problem with the task table not correctly setting `table.working = false`.  I see this in master too.  I have filed http://projects.theforeman.org/issues/19089 for this issue.

**Comment by ehelms** [comment]
The Nan came from this -- https://github.com/Katello/bastion/pull/183#issuecomment-290207011

**Comment by waldenraines** [comment]
> The Nan came from this -- #183 (comment)

I cannot reproduce this, can you still?  There were a lot of PRs in flight when this was written and perhaps there was some interdependence,

**Comment by jlsherrill** [comment]
overridden page size doesn't seem to be saved

**Comment by waldenraines** [comment]
@jlsherrill updated.

**Comment by jlsherrill** [comment]
seeing a couple issues that i don't think were there before:
1) The page count isn't selected anymore when navigating a page

2)
a) Navigate to a nutupane page with ~100 items
b) navigate to page 2
c) open an item details page
d) use breadcrumb to go back to the list
e) use the page nav at the bottom to go back to page 1

Results: you stay on page 2

**Comment by waldenraines** [comment]
> The page count isn't selected anymore when navigating to a page

Fixed.


> a) Navigate to a nutupane page with ~100 items
> b) navigate to page 2
> c) open an item details page
> d) use breadcrumb to go back to the list
> e) use the page nav at the bottom to go back to page 1
> 
> Results: you stay on page 2

This I cannot reproduce, could have been related to the fix for issue 1

**Comment by waldenraines** [comment]
[test]

**Comment by jlsherrill** [comment]
APJ

**Pull request merged**
