### PR TITLE
Refs #26206 - Adds CV solve deps param

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
@waldenraines thanks for merging! I was thinking the same thing, I think that ties in with the larger discussions around moving bastion to katello and moving it to webpack, hopefully something we can dig into more soon! :pray:

**Comment by johnpmitsch** [comment]
also @ehelms @waldenraines can I get a release?

**Comment by waldenraines** [comment]
> also @ehelms @waldenraines can I get a release?

Coming right up sir :fries: :smile:

**Comment by waldenraines** [comment]
Released [bastion 6.1.21](https://rubygems.org/gems/bastion/versions/6.1.21).

**Pull request merged**
