### PR TITLE
Fixes #16534: remove nutupane support from bastion

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/16534

Here is a page that points out the problems quite well (at 1280x800px):

screen shot 2016-09-13 at 12 05 25 pm

On this page I am attempting to add an erratum to a filter in the table at the bottom.  Notice how small that table is and how much I would have to scroll if I had a lot of errata.  Also note the double scrollbars.

### CODE REVIEW

**Comment by waldenraines** [comment]
CC: @Rohoover

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
I'm OK doing a special branch, we could also do new layouts in parallel in master to allow more piece-by-piece shifting of pages to new look and feel.

**Comment by waldenraines** [comment]
> I'm OK doing a special branch, we could also do new layouts in parallel in master to allow more piece-by-piece shifting of pages to new look and feel.

I had thought about that but it's going to be a lot easier to make nutupane unsupported and then replace it than support both for a while.

**Comment by ehelms** [comment]
What are we defining as unsupported here? Removing nutupane code and
layouts, not allowing new pages built with it or other? I was figuring we'd
want the old code around so pages keep working while we add new bits and
convert pages one by one to the new.

**Comment by waldenraines** [comment]
> What are we defining as unsupported here? Removing nutupane code and
> layouts, not allowing new pages built with it or other? I was figuring we'd
> want the old code around so pages keep working while we add new bits and
> convert pages one by one to the new.

That's why I created this branch.  My goal was quickly and easily replace nutupane.  This change will break all pages that use nutupane and they will need to be fixed in the corresponding katello branch.

**Comment by ehelms** [comment]
Which is a large orchestrated change that in the past has proved to have
its complications. I'm proposing we do it in a way that allows less
orchestrating and smaller atomic changes and reviews. We would be able to
add new code to Bastion without coordinating merges and convert individual
Katello pages allowing smaller diff and each page to get reviewed and
converted. If we are worried about ending up with half converted and he
other half not by next release we either make it a blocker, accept that to
get feedback or use a feature flag like we have before.

I'm mostly thinking about how we make this easiest on you, reviewers and
getting changes in quicker for faster feedback.

**Comment by waldenraines** [comment]
> I'm mostly thinking about how we make this easiest on you, reviewers and
> getting changes in quicker for faster feedback.

Fine.  I will keep nutupane in there for now and create this in parallel and then remove nutupane.  I think you're right that's probably a better approach than removing and adding in the same step.  You know me, I was just really excited to start deleting stuff.

Do you want me to reopen this against master then?

**Comment by ehelms** [comment]
I promise you we'll leave the final big delete for you to do :) Go for opening against master.

**Comment by waldenraines** [comment]
> I promise you we'll leave the final big delete for you to do :) Go for opening against master.

See https://github.com/Katello/bastion/pull/128

**Pull request closed without merging**
