### PR TITLE
Fixes #10399: Remove licenses from top of files.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by waldenraines** [comment]
I don't think theforeman-bot will link up with the issue without a # sign in the commit message (and even then only on the initial PR creation, I believe).

**Comment by waldenraines** [comment]
The copyright is still present in [`Gruntfile.js`](https://github.com/ehelms/bastion/blob/ab2e877acb9243bb9a7e0c9655e29002b9154936/Gruntfile.js)

**Comment by ehelms** [comment]
Good catch, I updated the issue and the commit message manually.

**Comment by waldenraines** [comment]
ACK

**Pull request merged**
