### PR TITLE
Refs #8039 - upgrade patternfly to version 1.1.3

### PR DESCRIPTION
**Pull request by waldenraines**
Upgrades patternfly to 1.1.3 and fix places where the upgrade broke
the UI.

http://projects.theforeman.org/issues/8039

Requires https://github.com/Katello/katello/pull/4760

### CODE REVIEW

**Comment by ehelms** [comment]
Could we bump to 1.1.2 since that is newer? Also, I think you are pulling in unneeded assets and pulling them into the wrong location if we were to need them. For example, bootstrap JS into the stylesheets directory -- https://github.com/Katello/bastion/pull/10/files#diff-91

**Comment by ehelms** [comment]
Not able to test this as I get -- `File to import not found or unreadable: bastion/font-awesome/scss/font-awesome.` This looks to be a result of your change to how the grunt bower task places assets down, which when looking at the change, I didn't understand why it was needed (especially in light of it changing the pathing)

**Comment by waldenraines** [comment]
@ehelms updated.  As discussed I just hardcoded the bastion paths in [patternfly.less](https://github.com/waldenraines/bastion/commit/f6f0d48c7b6358fa1fb2df5b8d5fc836f2adb478#diff-e0aa94c4092f0bb2a36af54b7c63dc87R4) for now such that this PR can be reviewed.

**Comment by waldenraines** [comment]
[test]

**Comment by jlsherrill** [comment]
Played around with this a bit and i could not find any issues. ACK from me

**Comment by ehelms** [comment]
ACK

**Pull request merged**
