### PR TITLE
Fixes #13170 - allow for using layout with assets independently

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by ehelms** [comment]
Looks OK, if you don't mind me asking, how do you intend to use this split ?

**Comment by tstrachota** [comment]
@ehelms oh sure, here's example how I use it in smart proxy show page to enable extending it with angular:
```ruby
    module SmartProxiesControllerExtensions
      extend ActiveSupport::Concern

      included do
        alias_method_chain :show, :content
      end

      def show_with_content
        render 'foreman/smart_proxies/show', :layout => 'katello/layouts/foreman_with_bastion'
      end
    end
```
The result is exactly the same page but with bastion loaded.

**Comment by ehelms** [comment]
Neat - I hadn't realized/seen that others were making use of Bastion to do UI features in other areas. Is this being done in a plugin or a PR to Foreman? You've piqued my curiosity more now :)

I can merge and build a new gem a little bit later today.

**Comment by ehelms** [comment]
ACK - thanks @tstrachota !

**Comment by ehelms** [comment]
bastion-3.0.1 should be available on rubygems

**Comment by tstrachota** [comment]
@ehelms great, thank you!

**Pull request merged**
