### PR TITLE
fixes #25035 - refactor multiselect and fix arrayToString

### PR DESCRIPTION
**Pull request by stbenjam**
arrayToString was oddly expecting an object, and this refactors mutliselect to be useful for my purposes. Neither of these appear to be used anywhere in Katello at the moment.

### CODE REVIEW

**Comment by stbenjam** [comment]
@Katello/ui Would someone mind reviewing this? Thanks! This is needed by https://github.com/Katello/katello/pull/7665

**Comment by jturel** [comment]
In the context of the katello pr you mentioned this works great. Maybe we should leave it open until it's totally ACK'd just in case this should need to change for whatever reason?

**Comment by jturel** [comment]
I also confirmed that the formatter & component changes are unused elsewhere so shouldn't break anything else

**Comment by stbenjam** [comment]
Thanks @jlsherrill

**Pull request merged**
