### PR TITLE
Fixes #16326: Move testing to Travis

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@waldenraines thoughts on this change?

**Comment by waldenraines** [comment]
@ehelms can you speak to the "why" of this change please.

**Comment by ehelms** [comment]
Remove pressure on Jenkins, in theory Travis shouldn't get as blocked as our Jenkins has been getting lately at times.

**Comment by waldenraines** [comment]
> Remove pressure on Jenkins, in theory Travis shouldn't get as blocked as our Jenkins has been getting lately at times.

Sounds good to me.  Will there be something following this to actually remove Jenkins?

**Comment by waldenraines** [comment]
ACK pending issue to remove Jenkins.

**Pull request closed without merging**
