### PR TITLE
Fixes #21076: add unregister_delete_host setting.

### PR DESCRIPTION
**Pull request by waldenraines**
http://projects.theforeman.org/issues/21076

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
ACK -- you could also include this directly from Katello via the include JS section to avoid having it live here disconnected from Katello code.

**Pull request merged**
