### PR TITLE
Fixes #10821: replace bst-infinite-scroll with ngInfiniteScroll.

### PR DESCRIPTION
**Pull request by waldenraines**
Eliminate several issues in bst-infinite-scroll by replacing it with
ngInfiniteScroll.

http://projects.theforeman.org/issues/10821

### CODE REVIEW

**Comment by waldenraines** [comment]
[test]

**Comment by ehelms** [comment]
Would you say this represents an interface change, enough to bump our major version?

**Comment by waldenraines** [comment]
> Would you say this represents an interface change, enough to bump our major version?

As far as using nutupane there really is no change, you'd use it the same way as you would before.  If you're using infinite-scroll directly then yeah, it would require a change on the part of the bastion consumer (read katello developers) since that directive is gone now.  

Even though there is really no need as of yet to bump the version for these types of changes (as katello is the only consumer of this project) if we want to establish that as a practice then I'm fine with it, numbers are free and plentiful.

**Comment by ehelms** [comment]
Thanks for the explanation. Practicing semver is good to practice (even if our audience is small) I think since it makes you think more about the types of changes being made. I'll update the issue when I add a 2.0.0 release.

**Comment by ehelms** [comment]
ACK - I will work on building and releasing 2.0.0, you'll likely need to update the Katello PR to adjust the requires on the gemspec and spec

**Pull request merged**
