### PR TITLE
Fixes #18030: use patternfly table classes.

### PR DESCRIPTION
**Pull request by waldenraines**
Instead of maintaining our own set of rules for tables under
.nutupane we should be using the classes from patternfly.

http://projects.theforeman.org/issues/18030

### CODE REVIEW

**Comment by ehelms** [comment]
Needs rebase

**Comment by ehelms** [comment]
screenshot from 2017-01-17 12-08-46

This is what I see when looking at a table with these changes. Is the intent for there to be gutters on the side?

**Comment by waldenraines** [comment]
> This is what I see when looking at a table with these changes. Is the intent for there to be gutters on the side?

See http://projects.theforeman.org/issues/18078

**Comment by waldenraines** [comment]
> Needs rebase

Done.

**Comment by ehelms** [comment]
Sorry, I meant the "gutters" between the edge of the browser and the start of the table. The table looks compacted to me and not a part of the page but more like a widget on the page which on this type page this is the page. I reached out to the Patternfly team for a full page view and this is what they pointed me to:

https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html

I think this jives with what I was thinking in that it feels more like the page itself.

**Comment by waldenraines** [comment]
> Sorry, I meant the "gutters" between the edge of the browser and the start of the table. The table looks compacted to me and not a part of the page but more like a widget on the page which on this type page this is the page. I reached out to the Patternfly team for a full page view and this is what they pointed me to:
> 
> https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html
> 
> I think this jives with what I was thinking in that it feels more like the page itself.

The table is an item on the page, it's not the page itself.  Also, these look the same to me, both have padding on the sides (due to the use of `.row` and `.col-sm-12`).  Can you please explain the difference?

**Comment by ehelms** [comment]
* The line across the top that goes side to side that separates the filters from the rest of the table. 
 * The use of white space vs gray space.
 * Bordering on the table and not the actions/filtering section.

The link from patternfly and the screenshot I posted do not look the same :)

The table is not our page but the table view is, which is the aspect I am speaking to (the totality of all pieces combined).

**Comment by waldenraines** [comment]
> The line across the top that goes side to side that separates the filters from the rest of the table.
> The use of white space vs gray space.
> Bordering on the table and not the actions/filtering section.
> The link from patternfly and the screenshot I posted do not look the same :)
> 
> The table is not our page but the table view is, which is the aspect I am speaking to (the totality of all pieces combined).

Gotcha, I thought you were talking about the table itself.  Updated the PR to use the `.table-view-pf-toolbar-external` class from the example.

**Comment by ehelms** [comment]
Looking good! Two questions:

 1) Seems like the table should be borderd if we are going based off of (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html)
 2) Are the gaps between serach bar, search button and dropdown intended?

screenshot from 2017-01-18 11-43-18

**Comment by waldenraines** [comment]
> Looking good! Two questions:
> 
> Seems like the table should be borderd if we are going based off of (https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/table-view-navbar.html)

See http://projects.theforeman.org/issues/18078

I plan on tackling that once all my non-nutupane katello changes are merged so I don't have to make these changes across several branches.

> Are the gaps between serach bar, search button and dropdown intended?

No, will fix.

**Comment by waldenraines** [comment]
@ehelms updated.

**Comment by ehelms** [comment]
Looks good! Test failure of some sort -- ACK once thats addressed.

**Comment by waldenraines** [comment]
[test]

**Comment by waldenraines** [comment]
[test]

**Pull request merged**
