### PR TITLE
Fixes #16296 - Pass content to errorCatcher

### PR DESCRIPTION
**Pull request by daviddavis**
This is a temporary fix to our local copy of ng-upload until https://github.com/twilson63/ngUpload/pull/133 is merged.

### CODE REVIEW

**Comment by waldenraines** [comment]
APJ/T

**Comment by ehelms** [comment]
@waldenraines I think we should remove this from our dependency list so that it does not get overriden until the official package carries. Thoughts?

**Comment by waldenraines** [comment]
> @waldenraines I think we should remove this from our dependency list so that it does not get overriden until the official package carries. Thoughts?

I don't like the idea of removing it but could we lock it to a specific version instead?

**Comment by ehelms** [comment]
@daviddavis

**Comment by daviddavis** [comment]
Not sure I fully understand but I updated packages.json to include the version we have..?

**Comment by daviddavis** [comment]
Ok, set the version of ng-upload in bower.json. Let me know if that's incorrect.

**Comment by daviddavis** [comment]
Ping @ehelms / @waldenraines

**Comment by waldenraines** [comment]
ACK

**Pull request merged**
