### PR TITLE
Fixes #26107 - Add readonly option to multiselect

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
Thanks @waldenraines. Can you also cut a release when you get a few minutes?

**Comment by waldenraines** [comment]
@jturel you may want to ask @ehelms if he can as I'm in the process of getting my sandbox set up after upgrading my fedora version.  I'm happy to do it but it may not be until Monday.

**Comment by jturel** [comment]
Monday's fine but if Eric sees this and can take care of it I wouldn't be disappointed.  😄

**Comment by waldenraines** [comment]
> Monday's fine but if Eric sees this and can take care of it I wouldn't be disappointed.

[bastion 6.1.20](https://rubygems.org/gems/bastion/versions/6.1.20) has been released.

**Pull request merged**
